version: 2.1
jobs:
  build-and-test:
    docker:
      - image: inpefess/python_with_provers
    steps:
      - checkout
      - run:
          name: use tox
          command: |
            pip install tox
            pyenv local 3.8.15 3.9.15 3.10.7
            tox
      - run:
          name: upload data to codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov
      - store_artifacts:
          path: build
      - store_test_results:
          path: test-results
workflows:
  main:
    jobs:
      - build-and-test
